-- ============================================================
-- CHANDA ENTERPRISES — REAL DATA IMPORT (v2, all 3 sheets)
-- 147 materials total, 32 suppliers
-- Stock Details + RM Sheets Details -> material_type = PRODUCTION
-- Consumable Items                  -> material_type = CONSUMABLE
-- Opening Qty = current Available/Balance Qty as of the file's date (13-07-2026)
-- Historical purchase/issue records NOT backfilled (see README)
-- ============================================================

-- Suppliers (from Party Name columns)
INSERT INTO suppliers (supplier_name) VALUES ('A K Engg Works') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('ANS Steel Tubes') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('Aditya Wire') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('Apex Auto') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('Bhushan Power') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('Dev Automates') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('Geeta Packaging') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('Hiranya Enterprises') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('J C ENTERPRISES') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('J K Auto Industries') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('J P INDUSTRIES') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('Jindal Steel') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('Kay Kay Machenical') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('Kissui Metaliks') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('Marit Packaging') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('Maruichi Kuma') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('Poonil Products') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('R V Wire Industries') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('Rank Furmishers') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('S M Motor') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('Satnam Industries') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('Shree Bala Ji') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('Shree Balaji Tech India') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('Shree Krishna PKG') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('Sneha Engineering Works') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('Suraj Auto Products') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('Tata Steel') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('Uttam Stripes') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('Uttam Strips') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('Vardhman Trading Co.') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('Vee Kay Industries') ON CONFLICT (supplier_name) DO NOTHING;
INSERT INTO suppliers (supplier_name) VALUES ('a') ON CONFLICT (supplier_name) DO NOTHING;

-- Materials (all 3 sheets)
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC001', '50.8X1.2X189', 'SS/ERW Pipe', 'PRODUCTION', 'SS 409L', NULL, 1000.0, 5000.0, 5740.0, 5740.0, 'C-17,20,23,26,29,Pallet', (SELECT id FROM suppliers WHERE supplier_name = 'Kissui Metaliks'), 400.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC002', '22.2x1.5x200', 'SS/ERW Pipe', 'PRODUCTION', 'SS 409L', NULL, 1000.0, 5000.0, 4000.0, 4000.0, 'C-18,Floor', (SELECT id FROM suppliers WHERE supplier_name = 'Kissui Metaliks'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC003', '19.05x1.2x140', 'SS/ERW Pipe', 'PRODUCTION', 'SS 409L', NULL, 500.0, 3000.0, 0.0, 0.0, 'C-21', (SELECT id FROM suppliers WHERE supplier_name = 'Maruichi Kuma'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC004', '28.6X1.5X68', 'SS/ERW Pipe', 'PRODUCTION', 'SS 409L', NULL, 500.0, 5000.0, 0.0, 0.0, 'C-24,25', (SELECT id FROM suppliers WHERE supplier_name = 'Maruichi Kuma'), 400.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC005', '28.6X1.5X109', 'SS/ERW Pipe', 'PRODUCTION', 'SS 409L', NULL, 500.0, 5000.0, 0.0, 0.0, 'C-19,22', (SELECT id FROM suppliers WHERE supplier_name = 'Maruichi Kuma'), 400.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC006', '12X0.8X496 (COATTED TUBE)', 'SS/ERW Pipe', 'PRODUCTION', 'MS PIPE', NULL, 500.0, 8700.0, 2900.0, 2900.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'ANS Steel Tubes'), 1200.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC007', '22.2x2x807', 'SS/ERW Pipe', 'PRODUCTION', 'ERW-1', NULL, 1000.0, 10000.0, 3250.0, 3250.0, 'C- 16', (SELECT id FROM suppliers WHERE supplier_name = 'Uttam Stripes'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC008', '19.05X1.4X315', 'SS/ERW Pipe', 'PRODUCTION', 'ERW-3', NULL, 2000.0, 15000.0, 6371.0, 6371.0, 'C-27,30,31,Floor', (SELECT id FROM suppliers WHERE supplier_name = 'Shree Bala Ji'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC009', '19.05X1.4X225', 'SS/ERW Pipe', 'PRODUCTION', 'ERW-3', NULL, 2000.0, 15000.0, 1500.0, 1500.0, 'C-33,34,35 FLOOR', (SELECT id FROM suppliers WHERE supplier_name = 'Shree Bala Ji'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC010', '22.2x2x816', 'SS/ERW Pipe', 'PRODUCTION', 'ERW-MA', NULL, 0.0, 2000.0, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Bhushan Power'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC011', '22.2x2x816', 'SS/ERW Pipe', 'PRODUCTION', 'ERW-MA', NULL, 0, 1000, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Tata Steel'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC012', '22.2x2x841', 'SS/ERW Pipe', 'PRODUCTION', 'ERW-MA', NULL, 1000.0, 10000.0, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Tata Steel'), 400.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC013', '22.2x2x841', 'SS/ERW Pipe', 'PRODUCTION', 'ERW-2', NULL, 0, 17925.0, 5975.0, 5975.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Bhushan Power'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC014', '22.23X2X825', 'SS/ERW Pipe', 'PRODUCTION', 'ERW-2', NULL, 500.0, 2000.0, 0.0, 0.0, 'C-1,3,5', (SELECT id FROM suppliers WHERE supplier_name = 'Tata Steel'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC015', '22.23X2X825', 'SS/ERW Pipe', 'PRODUCTION', 'ERW-2', NULL, 0, 1000, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Bhushan Power'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC016', '22.23x2.00x930', 'SS/ERW Pipe', 'PRODUCTION', 'ERW-2', NULL, 0.0, 1500.0, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Bhushan Power'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC017', '22.23X1.92X788', 'SS/ERW Pipe', 'PRODUCTION', 'ERW-1', NULL, 0.0, 1500.0, 2240.0, 2240.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Bhushan Power'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC018', '22.23X1.92X887', 'SS/ERW Pipe', 'PRODUCTION', 'ERW-1', NULL, 0.0, 1500.0, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Bhushan Power'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC019', '15.88X1.8X100', 'SS/ERW Pipe', 'PRODUCTION', 'SS 409L', NULL, 2000.0, 15000.0, 9000.0, 9000.0, 'C-37,39', (SELECT id FROM suppliers WHERE supplier_name = 'Shree Balaji Tech India'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC020', '22.23X2X858', 'SS/ERW Pipe', 'PRODUCTION', 'ERW-2', NULL, 0, 1000, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Tata Steel'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC021', '22.2x2x874', 'SS/ERW Pipe', 'PRODUCTION', 'ERW-1', NULL, 0.0, 2000.0, 400.0, 400.0, 'C-53', (SELECT id FROM suppliers WHERE supplier_name = 'Bhushan Power'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC022', '35X1.2X2000', 'SS/ERW Pipe', 'PRODUCTION', 'SS 409L', NULL, 10.0, 200.0, 25.0, 25.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Maruichi Kuma'), 10.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC023', '15.88X1.8X3000', 'SS/ERW Pipe', 'PRODUCTION', 'ERW-1', NULL, 0, 1000, 10.0, 10.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Poonil Products'), 100.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC024', 'BUSH 14 MM', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 1000.0, 10000.0, 0.0, 0.0, 'C-3', (SELECT id FROM suppliers WHERE supplier_name = 'A K Engg Works'), 960.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC025', 'BUSH 14MM', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 0, 9600.0, 3200.0, 3200.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Satnam Industries'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC026', 'BUSH 15MM', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 1000.0, 10000.0, 0.0, 0.0, 'C-4', (SELECT id FROM suppliers WHERE supplier_name = 'A K Engg Works'), 960.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC027', 'BUSH 15MM', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 0, 1000, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'J P INDUSTRIES'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC028', 'BUSH 15MM', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 0, 1000, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Satnam Industries'), 960.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC029', 'CLASSIC BUH 350', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 1000.0, 5000.0, 2470.0, 2470.0, 'C-8', (SELECT id FROM suppliers WHERE supplier_name = 'A K Engg Works'), 240.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC030', 'CLASSIC BUH 350', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 0, 1000, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'J P INDUSTRIES'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC031', 'CLASSIC BUH 350', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 0, 1000, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'J K Auto Industries'), 240.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC032', 'BUSH-N360', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 0, 8286.0, 2762.0, 2762.0, 'C-7', (SELECT id FROM suppliers WHERE supplier_name = 'A K Engg Works'), 800.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC033', 'LONG BUSH J1A', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 2000.0, 15000.0, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Satnam Industries'), 800.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC034', 'LONG BUSH J1A', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 0, 1000, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Suraj Auto Products'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC035', 'LONG BUSH J1A', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 0, 1000, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'S M Motor'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC036', 'SPACER BUSH  35.5X9.5  (Medium)', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 2000.0, 10000.0, 6000.0, 6000.0, 'Floor', (SELECT id FROM suppliers WHERE supplier_name = 'S M Motor'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC037', 'SOCKER PIN LH 17*82', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 2000.0, 10000.0, 0.0, 0.0, 'C-28', (SELECT id FROM suppliers WHERE supplier_name = 'Dev Automates'), 400.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC038', 'SOCKER PIN LH 17*82', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 0, 1000, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Apex Auto'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC039', 'SOCKER PIN RH 17*75', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 2000.0, 10000.0, 400.0, 400.0, 'Floor', (SELECT id FROM suppliers WHERE supplier_name = 'Dev Automates'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC040', 'SOCKER PIN RH 17*75', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 0, 1000, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Apex Auto'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC041', 'MOUNTING BRACKET J1A', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 1000.0, 10000.0, 6000.0, 6000.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Kay Kay Machenical'), 250.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC042', 'MOUNTING BRACKET P5AB', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 1000.0, 10000.0, 2200.0, 2200.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Kay Kay Machenical'), 100.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC043', 'HOLDING BRACKET J1A', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 1000.0, 10000.0, 3000.0, 3000.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Kay Kay Machenical'), 120.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC044', 'HOLDING BRACKET P5AB', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 1000.0, 10000.0, 4000.0, 4000.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Kay Kay Machenical'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC045', 'Rivit', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 500.0, 4000.0, 3000.0, 3000.0, NULL, NULL, 1000.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC046', 'HOLDING BRACKET J1D3', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 1000.0, 10000.0, 7000.0, 7000.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Sneha Engineering Works'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC047', 'LOWER BRACKET J1D3', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 1000.0, 10000.0, 5300.0, 5300.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Sneha Engineering Works'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC048', 'MOUNTING BRACKET J1D3', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 1000.0, 10000.0, 7000.0, 7000.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Sneha Engineering Works'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC049', 'ANGLE 75X75X970', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 50.0, 500.0, 575.0, 575.0, 'C-15', NULL, 25.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC050', 'ANGLE 75X75X670', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 50.0, 500.0, 375.0, 375.0, 'C-20', NULL, 30.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC051', 'MIG WIRE 0.8MM (MS)', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 5.0, 20.0, 6.0, 6.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'R V Wire Industries'), 4.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC052', 'MIG WIRE 0.8MM (SS)', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 5.0, 20.0, 8.0, 8.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Aditya Wire'), 2.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC053', 'Rivit Black', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 0, 1000, 0.0, 0.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC054', 'LONG BUSH SAMPLE', 'SS/ERW Pipe', 'PRODUCTION', 'BOP', NULL, 0, 1000, 90.0, 90.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC055', 'BOX700X350X185', 'SS/ERW Pipe', 'PRODUCTION', 'BOX', NULL, 0, 1000, 140.0, 140.0, NULL, NULL, 20.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC056', 'BOX700X350X185', 'SS/ERW Pipe', 'PRODUCTION', 'BOX', NULL, 0, 1000, 270.0, 270.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Shree Krishna PKG'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC057', 'BOX730X310X160 (White) HDP', 'SS/ERW Pipe', 'PRODUCTION', 'BOX', NULL, 50.0, 250.0, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Hiranya Enterprises'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC058', 'BOX730X310X160 (White) HDP', 'SS/ERW Pipe', 'PRODUCTION', 'BOX', NULL, 0, 1000, 0.0, 0.0, 'C-9', (SELECT id FROM suppliers WHERE supplier_name = 'Shree Krishna PKG'), 50.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC059', 'BOX730X310X160 (Brown)', 'SS/ERW Pipe', 'PRODUCTION', 'BOX', NULL, 0, 1000, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Shree Krishna PKG'), 50.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC060', 'BOX770X310X105(5PLY) White', 'SS/ERW Pipe', 'PRODUCTION', 'BOX', NULL, 150.0, 500.0, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Shree Krishna PKG'), 10.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC061', 'BOX340X320X200', 'SS/ERW Pipe', 'PRODUCTION', 'BOX', NULL, 0, 1000, 261.0, 261.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Geeta Packaging'), 40.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC062', 'BOX770X310X160 HDPE(WHITE) 7 PLY', 'SS/ERW Pipe', 'PRODUCTION', 'BOX', NULL, 0, 1000, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Geeta Packaging'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC063', 'BOX770X310X160 HDPE(WHITE) 7 PLY', 'SS/ERW Pipe', 'PRODUCTION', 'BOX', NULL, 0, 1000, 130.0, 130.0, 'C-20.24', (SELECT id FROM suppliers WHERE supplier_name = 'Shree Krishna PKG'), 30.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC064', 'BOX850X350X200 HDPE(WHITE) 7 PLY', 'SS/ERW Pipe', 'PRODUCTION', 'BOX', NULL, 0, 1000, 0.0, 0.0, 'C-22', (SELECT id FROM suppliers WHERE supplier_name = 'Shree Krishna PKG'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC065', 'BOX-600X235X125 BROWN', 'SS/ERW Pipe', 'PRODUCTION', 'BOX', NULL, 0, 1000, 0.0, 0.0, 'C-14', (SELECT id FROM suppliers WHERE supplier_name = 'Geeta Packaging'), 90.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC066', 'BOX-600X235X125 BROWN', 'SS/ERW Pipe', 'PRODUCTION', 'BOX', NULL, 0, 1000, 0.0, 0.0, 'C-14', (SELECT id FROM suppliers WHERE supplier_name = 'Shree Krishna PKG'), 90.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC067', 'BOX JALI 24 PCS', 'SS/ERW Pipe', 'PRODUCTION', 'BOX', NULL, 10.0, 100.0, 10.0, 10.0, 'C-30', NULL, 8.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC068', 'BOX JALI 15 PCS', 'SS/ERW Pipe', 'PRODUCTION', 'BOX', NULL, 10.0, 100.0, 20.0, 20.0, NULL, NULL, 8.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC069', 'PARTITION', 'SS/ERW Pipe', 'PRODUCTION', 'BOX', NULL, 10.0, 100.0, 540.0, 540.0, NULL, NULL, 20.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC070', 'BOX690X535X450', 'SS/ERW Pipe', 'PRODUCTION', 'BOX', NULL, 5.0, 50.0, 164.0, 164.0, 'Floor', NULL, 4.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC071', 'HEX WELD NUTM8', 'SS/ERW Pipe', 'PRODUCTION', 'NUTS', NULL, 5000.0, 15000.0, 40000.0, 40000.0, 'C-18', NULL, 5000.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC072', 'HEX WELD NUTM6', 'SS/ERW Pipe', 'PRODUCTION', 'NUTS', NULL, 0, 51000.0, 17000.0, 17000.0, 'C-13', NULL, 600.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC073', 'HEX WELD NUTM5', 'SS/ERW Pipe', 'PRODUCTION', 'NUTS', NULL, 0, 1000, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'a'), 600.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC074', 'CO2 GAS', 'SS/ERW Pipe', 'PRODUCTION', 'GAS', NULL, 4.0, 10.0, 8.0, 8.0, NULL, NULL, 8.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC075', 'ARGON GAS', 'SS/ERW Pipe', 'PRODUCTION', 'GAS', NULL, 2.0, 8.0, 3.0, 3.0, NULL, NULL, 3.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC076', 'BUBBLE BAG 28X3', 'SS/ERW Pipe', 'PRODUCTION', 'BUBBLE BAG', NULL, 1000.0, 10000.0, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Vee Kay Industries'), 1000.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC077', 'BUBBLE BAG 300x300', 'SS/ERW Pipe', 'PRODUCTION', 'BUBBLE BAG', NULL, 500.0, 5000.0, 3500.0, 3500.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Vee Kay Industries'), 1000.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC078', 'BUBBLE BAG 40X3', 'SS/ERW Pipe', 'PRODUCTION', 'BUBBLE BAG', NULL, 2000.0, 15000.0, 18500.0, 18500.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Vee Kay Industries'), 1500.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC079', 'POLYTHENE 20X27', 'SS/ERW Pipe', 'PRODUCTION', 'POLYTHENE', NULL, 0, 1000, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Marit Packaging'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC080', 'POLYTHENE 630X890 Breather Pipe', 'SS/ERW Pipe', 'PRODUCTION', 'POLYTHENE', NULL, 10.0, 100.0, 35.0, 35.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Marit Packaging'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC081', 'POLYTHENE 40X3 Plain', 'SS/ERW Pipe', 'PRODUCTION', 'POLYTHENE', NULL, 10.0, 100.0, 56.0, 56.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC082', 'POLYTHENE 300X300 Plain', 'SS/ERW Pipe', 'PRODUCTION', 'POLYTHENE', NULL, 0, 1000, 0.0, 0.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC083', 'POLYTHENE 15 Inch', 'SS/ERW Pipe', 'PRODUCTION', 'POLYTHENE', NULL, 0, 1000, 1.0, 1.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Marit Packaging'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC084', 'WOODEN PILOTS', 'SS/ERW Pipe', 'PRODUCTION', 'WOODEN', NULL, 2.0, 15.0, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Rank Furmishers'), 4.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('MC085', 'P5AB RIM TAPE', 'SS/ERW Pipe', 'PRODUCTION', 'TAPE', NULL, 0, 54000.0, 18000.0, 18000.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('RM001', 'HROP 2MM 1250X2500', 'RM Sheet', 'PRODUCTION', 'HROP', '1250X2500', 0, 500, 120.0, 120.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Uttam Strips'), 7.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('RM002', 'HR 2.3MM 1250X2500', 'RM Sheet', 'PRODUCTION', 'HR', '1250X2500', 0, 500, 0.0, 0.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('RM003', 'HR 3.00 MM 1250X2500', 'RM Sheet', 'PRODUCTION', 'HR', '1250X2500', 0, 500, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Uttam Strips'), 2.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('RM004', 'HR 1.6 MM 1250X2500', 'RM Sheet', 'PRODUCTION', 'HR', '1250X2500', 0, 500, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Vardhman Trading Co.'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('RM005', 'CR 1.6 MM 1250X2500', 'RM Sheet', 'PRODUCTION', 'CR', '1250X2500', 0, 500, 1.0, 1.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('RM006', 'CR 1.5MM 1250X2500', 'RM Sheet', 'PRODUCTION', 'CR', '1250X2500', 0, 500, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Vardhman Trading Co.'), 11.5) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('RM007', 'CR 1.5MM 1250X2295', 'RM Sheet', 'PRODUCTION', 'CR', '1250X2295', 0, 500, 25.0, 25.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'J C ENTERPRISES'), 12.5) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('RM008', 'CR 1.0MM 1250X2500', 'RM Sheet', 'PRODUCTION', 'CR', '1250X2500', 0, 500, 2.0, 2.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Vardhman Trading Co.'), 0.5) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('RM009', 'CR 0.8MM 1250X2220', 'RM Sheet', 'PRODUCTION', 'CR', '1250X2220', 0, 500, 0.0, 0.0, 'Floor', (SELECT id FROM suppliers WHERE supplier_name = 'J C ENTERPRISES'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('RM010', 'CR 0.8MM 1250X2500', 'RM Sheet', 'PRODUCTION', 'CR', '1250X2500', 0, 500, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Vardhman Trading Co.'), 7.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('RM011', 'CR 0.5 MM 1250X2500', 'RM Sheet', 'PRODUCTION', 'CR', '1250X2500', 0, 500, 1.0, 1.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Vardhman Trading Co.'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('RM012', 'CR 0.7MM 1250X2420', 'RM Sheet', 'PRODUCTION', 'CR', '1250X2420', 0, 500, 19.0, 19.0, 'Reject', (SELECT id FROM suppliers WHERE supplier_name = 'Vardhman Trading Co.'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('RM013', 'CR 0.7MM 1250X2422', 'RM Sheet', 'PRODUCTION', 'CR', '1250X2422', 0, 500, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'J C ENTERPRISES'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('RM014', 'SS 0.5 MM 130X1250', 'RM Sheet', 'PRODUCTION', 'SS', '130X1250', 0, 500, 0.0, 0.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('RM015', 'SS 1.5MM 1250x1500', 'RM Sheet', 'PRODUCTION', 'SS', '1250x1500', 0, 500, 11.0, 11.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Jindal Steel'), NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('RM016', 'S S 1.2 MM 1250X2500', 'RM Sheet', 'PRODUCTION', 'S S', '1250X2500', 0, 500, 0.0, 0.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Jindal Steel'), 34.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('RM017', 'S S 1.5 MM 1250X2500', 'RM Sheet', 'PRODUCTION', 'S S', '1250X2500', 0, 500, 30.0, 30.0, NULL, (SELECT id FROM suppliers WHERE supplier_name = 'Jindal Steel'), 34.0) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('RM018', 'RM Sheet 18', 'RM Sheet', 'PRODUCTION', NULL, NULL, 0, 500, 0, 0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('RM019', 'RM Sheet 19', 'RM Sheet', 'PRODUCTION', NULL, NULL, 0, 500, 0, 0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('RM020', 'RM Sheet 20', 'RM Sheet', 'PRODUCTION', NULL, NULL, 0, 500, 0, 0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('RM021', 'RM Sheet 21', 'RM Sheet', 'PRODUCTION', NULL, NULL, 0, 500, 0, 0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('RM022', 'RM Sheet 22', 'RM Sheet', 'PRODUCTION', NULL, NULL, 0, 500, 0, 0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('RM023', 'RM Sheet 23', 'RM Sheet', 'PRODUCTION', NULL, NULL, 0, 500, 0, 0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('RM024', 'RM Sheet 24', 'RM Sheet', 'PRODUCTION', NULL, NULL, 0, 500, 0, 0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN001', 'OLD DHOTI', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 0.0, 0.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN002', 'KNITTED HAND GLOVES', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 0.0, 0.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN003', 'LEATHER APPRON', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 0.0, 0.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN004', 'CUTTING CLOTH', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 0.0, 0.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN005', 'LEATHER HAND GLOVES', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 5.0, 5.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN006', 'canvas sleevs [ baaju ]', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 0.0, 0.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN007', 'HSS DRILL 6.2 MM', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 40.0, 40.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN008', 'HSS DRILL 5.1 MM', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 60.0, 60.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN009', 'HSS DRILL 5.2 MM', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 60.0, 60.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN010', 'HSS DRILL 4.1 MM', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 0.0, 0.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN011', 'HSS DRILL 8.2 MM', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 0.0, 0.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN012', 'HSS DRILL 6.5 MM', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 0.0, 0.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN013', 'HSS DRILL 5.3 MM', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 0.0, 0.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN014', 'HSS DRILL 5.00 MM', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 10.0, 10.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN015', 'GULLY SMALL', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 20.0, 20.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN016', 'GULLY BIG', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 20.0, 20.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN017', 'FLAP DISC ''''4''''''''', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 60.0, 60.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN018', 'PARTING WHEEL 4''''', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 10.0, 10.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN019', 'PATTE 80G', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 14.0, 14.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN020', 'PATTE 178G', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 30.0, 30.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN021', 'EMERY BELT 120', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 25.0, 25.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN022', 'EMERY BELT 320', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 20.0, 20.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN023', 'EMERY BELT 220', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 30.0, 30.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN024', 'EMERY BELT 80', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 17.0, 17.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN025', 'White Goggle', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 15.0, 15.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN026', 'White Glass', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 300.0, 300.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN027', 'Grinding Wheel', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 8.0, 8.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN028', 'Straping Roll White', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 9.0, 9.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN029', 'Straping Roll Green', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 1.0, 1.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN030', 'Plastic Packing Bag (Katte)', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 0.0, 0.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN031', 'Brown Tap 2"', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 40.0, 40.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN032', 'Hdrolic oil', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 0.0, 0.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN033', 'lub oil 40 no', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 0.0, 0.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN034', 'EMREY PAPER 220', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 5.0, 5.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN035', 'EMREY PAPER 320', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 10.0, 10.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN036', 'MOUNTING WHEEL (KULFI)', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 4.0, 4.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN037', 'Rust Oil', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 30.0, 30.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;
INSERT INTO materials (material_code, material_name, category, material_type, grade, size, min_qty, max_qty, opening_qty, current_qty, rack, supplier_id, per_day_req) VALUES ('CN038', 'BLACK GOGGLE', 'Consumable / Safety Item', 'CONSUMABLE', NULL, NULL, NULL, NULL, 1.0, 1.0, NULL, NULL, NULL) ON CONFLICT (material_code) DO NOTHING;

-- Import complete: 147 materials, 32 suppliers
-- Data-quality fixes applied: 115 (see comments below, review manually)
-- REVIEW: 12X0.8X496 (COATTED TUBE) -- max_qty missing/invalid -> set to 8700.0 (REVIEW MANUALLY)
-- REVIEW: 22.2x2x816 -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: 22.2x2x816 -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: 22.2x2x841 -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: 22.2x2x841 -- max_qty missing/invalid -> set to 17925.0 (REVIEW MANUALLY)
-- REVIEW: 22.23X2X825 -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: 22.23X2X825 -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: 22.23X2X858 -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: 22.23X2X858 -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: 15.88X1.8X3000 -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: 15.88X1.8X3000 -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: BUSH 14MM -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: BUSH 14MM -- max_qty missing/invalid -> set to 9600.0 (REVIEW MANUALLY)
-- REVIEW: BUSH 15MM -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: BUSH 15MM -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: BUSH 15MM -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: BUSH 15MM -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: CLASSIC BUH 350 -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: CLASSIC BUH 350 -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: CLASSIC BUH 350 -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: CLASSIC BUH 350 -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: BUSH-N360 -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: BUSH-N360 -- max_qty missing/invalid -> set to 8286.0 (REVIEW MANUALLY)
-- REVIEW: LONG BUSH J1A -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: LONG BUSH J1A -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: LONG BUSH J1A -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: LONG BUSH J1A -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: SOCKER PIN LH 17*82 -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: SOCKER PIN LH 17*82 -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: SOCKER PIN RH 17*75 -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: SOCKER PIN RH 17*75 -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: Rivit Black -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: Rivit Black -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: LONG BUSH SAMPLE -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: LONG BUSH SAMPLE -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: BOX700X350X185 -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: BOX700X350X185 -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: BOX700X350X185 -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: BOX700X350X185 -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: BOX730X310X160 (White) HDP -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: BOX730X310X160 (White) HDP -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: BOX730X310X160 (Brown) -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: BOX730X310X160 (Brown) -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: BOX340X320X200 -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: BOX340X320X200 -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: BOX770X310X160 HDPE(WHITE) 7 PLY -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: BOX770X310X160 HDPE(WHITE) 7 PLY -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: BOX770X310X160 HDPE(WHITE) 7 PLY -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: BOX770X310X160 HDPE(WHITE) 7 PLY -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: BOX850X350X200 HDPE(WHITE) 7 PLY -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: BOX850X350X200 HDPE(WHITE) 7 PLY -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: BOX-600X235X125 BROWN -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: BOX-600X235X125 BROWN -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: BOX-600X235X125 BROWN -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: BOX-600X235X125 BROWN -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: HEX WELD NUTM6 -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: HEX WELD NUTM6 -- max_qty missing/invalid -> set to 51000.0 (REVIEW MANUALLY)
-- REVIEW: HEX WELD NUTM5 -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: HEX WELD NUTM5 -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: POLYTHENE 20X27 -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: POLYTHENE 20X27 -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: POLYTHENE 300X300 Plain -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: POLYTHENE 300X300 Plain -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: POLYTHENE 15 Inch -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: POLYTHENE 15 Inch -- max_qty missing/invalid -> set to 1000 (REVIEW MANUALLY)
-- REVIEW: P5AB RIM TAPE -- min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: P5AB RIM TAPE -- max_qty missing/invalid -> set to 54000.0 (REVIEW MANUALLY)
-- REVIEW: HROP 2MM 1250X2500 -- RM sheet min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: HROP 2MM 1250X2500 -- RM sheet max_qty missing/invalid -> set to 500 (REVIEW MANUALLY)
-- REVIEW: HR 2.3MM 1250X2500 -- RM sheet min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: HR 2.3MM 1250X2500 -- RM sheet max_qty missing/invalid -> set to 500 (REVIEW MANUALLY)
-- REVIEW: HR 3.00 MM 1250X2500 -- RM sheet min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: HR 3.00 MM 1250X2500 -- RM sheet max_qty missing/invalid -> set to 500 (REVIEW MANUALLY)
-- REVIEW: HR 1.6 MM 1250X2500 -- RM sheet min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: HR 1.6 MM 1250X2500 -- RM sheet max_qty missing/invalid -> set to 500 (REVIEW MANUALLY)
-- REVIEW: CR 1.6 MM 1250X2500 -- RM sheet min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: CR 1.6 MM 1250X2500 -- RM sheet max_qty missing/invalid -> set to 500 (REVIEW MANUALLY)
-- REVIEW: CR 1.5MM 1250X2500 -- RM sheet min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: CR 1.5MM 1250X2500 -- RM sheet max_qty missing/invalid -> set to 500 (REVIEW MANUALLY)
-- REVIEW: CR 1.5MM 1250X2295 -- RM sheet min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: CR 1.5MM 1250X2295 -- RM sheet max_qty missing/invalid -> set to 500 (REVIEW MANUALLY)
-- REVIEW: CR 1.0MM 1250X2500 -- RM sheet min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: CR 1.0MM 1250X2500 -- RM sheet max_qty missing/invalid -> set to 500 (REVIEW MANUALLY)
-- REVIEW: CR 0.8MM 1250X2220 -- RM sheet min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: CR 0.8MM 1250X2220 -- RM sheet max_qty missing/invalid -> set to 500 (REVIEW MANUALLY)
-- REVIEW: CR 0.8MM 1250X2500 -- RM sheet min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: CR 0.8MM 1250X2500 -- RM sheet max_qty missing/invalid -> set to 500 (REVIEW MANUALLY)
-- REVIEW: CR 0.5 MM 1250X2500 -- RM sheet min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: CR 0.5 MM 1250X2500 -- RM sheet max_qty missing/invalid -> set to 500 (REVIEW MANUALLY)
-- REVIEW: CR 0.7MM 1250X2420 -- RM sheet min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: CR 0.7MM 1250X2420 -- RM sheet max_qty missing/invalid -> set to 500 (REVIEW MANUALLY)
-- REVIEW: CR 0.7MM 1250X2422 -- RM sheet min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: CR 0.7MM 1250X2422 -- RM sheet max_qty missing/invalid -> set to 500 (REVIEW MANUALLY)
-- REVIEW: SS 0.5 MM 130X1250 -- RM sheet min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: SS 0.5 MM 130X1250 -- RM sheet max_qty missing/invalid -> set to 500 (REVIEW MANUALLY)
-- REVIEW: SS 1.5MM 1250x1500 -- RM sheet min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: SS 1.5MM 1250x1500 -- RM sheet max_qty missing/invalid -> set to 500 (REVIEW MANUALLY)
-- REVIEW: S S 1.2 MM 1250X2500 -- RM sheet min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: S S 1.2 MM 1250X2500 -- RM sheet max_qty missing/invalid -> set to 500 (REVIEW MANUALLY)
-- REVIEW: S S 1.5 MM 1250X2500 -- RM sheet min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: S S 1.5 MM 1250X2500 -- RM sheet max_qty missing/invalid -> set to 500 (REVIEW MANUALLY)
-- REVIEW: RM Sheet 18 -- RM sheet min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: RM Sheet 18 -- RM sheet max_qty missing/invalid -> set to 500 (REVIEW MANUALLY)
-- REVIEW: RM Sheet 19 -- RM sheet min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: RM Sheet 19 -- RM sheet max_qty missing/invalid -> set to 500 (REVIEW MANUALLY)
-- REVIEW: RM Sheet 20 -- RM sheet min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: RM Sheet 20 -- RM sheet max_qty missing/invalid -> set to 500 (REVIEW MANUALLY)
-- REVIEW: RM Sheet 21 -- RM sheet min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: RM Sheet 21 -- RM sheet max_qty missing/invalid -> set to 500 (REVIEW MANUALLY)
-- REVIEW: RM Sheet 22 -- RM sheet min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: RM Sheet 22 -- RM sheet max_qty missing/invalid -> set to 500 (REVIEW MANUALLY)
-- REVIEW: RM Sheet 23 -- RM sheet min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: RM Sheet 23 -- RM sheet max_qty missing/invalid -> set to 500 (REVIEW MANUALLY)
-- REVIEW: RM Sheet 24 -- RM sheet min_qty missing -> set to 0 (REVIEW MANUALLY)
-- REVIEW: RM Sheet 24 -- RM sheet max_qty missing/invalid -> set to 500 (REVIEW MANUALLY)